sudo: required
services:
  - docker

before_install:
  - docker pull gcr.io/cpp-projects/cpp-ci:1

script:
  - >
    docker run -v `pwd`:/libwhereami gcr.io/cpp-projects/cpp-ci:1 /bin/bash -c "
    wget https://github.com/puppetlabs/leatherman/releases/download/${LEATHERMAN_VERSION}/leatherman.tar.gz &&
    tar xzvf leatherman.tar.gz --strip 1 -C / &&
    cd /libwhereami &&
    cmake $EXTRA_VARS . &&
    mkdir dest &&
    make $TARGET DESTDIR=/libwhereami/dest VERBOSE=1 -j2 &&
    { [[ '$COVERALLS' != 'ON' ]] || coveralls --gcov-options '\-lp' -r . -b . -e src -e vendor >/dev/null || true; }
    "

env:
  global:
    - LEATHERMAN_VERSION=1.4.0
  matrix:
    - TARGET=cpplint
    - TARGET=cppcheck
    - TARGET="all test install ARGS=-V" EXTRA_VARS="-DBOOST_STATIC=ON"
    - TARGET="all test install ARGS=-V" EXTRA_VARS="-DBOOST_STATIC=ON -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON" COVERALLS=ON
